version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: