version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

  # GPT-OSS inference server (GGUF local OpenAI-compatible)
  gpt-oss:
    build:
      context: .
      dockerfile: Dockerfile.gguf
    environment:
      - MODEL_PATH=${MODEL_PATH:-/models/gpt-oss-20b-MXFP4.gguf}
      - THREADS=${THREADS:-8}
      - CTX=${CTX:-1024}
      - GPU_LAYERS=${GPU_LAYERS:-35}
    ports:
      - "8000:8000"
    volumes:
      - "D:\\models\\gpt-oss:/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Monitor web service
  api-monitor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres port=5432 user=monitor password=password dbname=api_monitor sslmode=disable
      - AI_ENABLED=true
      - AI_BASE_URL=http://gpt-oss:8000
      - AI_API_KEY=demo-key
      - AI_MODEL=gpt-oss-20b
      - WEB_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
      gpt-oss:
        condition: service_healthy
    volumes:
      - ./web:/app/web

volumes:
  postgres_data:
  model_cache: